import { z } from "zod";

import {
  MOBILE_PILOT_APP_DATA_SCHEMA_VERSION,
  MOBILE_PILOT_RECOVERY_COPY_EXPORT_VERSION,
} from "../../domain/export/MobilePilotRecoveryCopy";
import { harvestUnitSchema } from "../../domain/validation/harvestValidation";

const isoDateTimeString = z.string().min(1);

const farmSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  createdAt: isoDateTimeString,
  corePlacesSetupCompletedAt: isoDateTimeString.optional(),
});

const locationSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  name: z.string().min(1),
  kind: z.enum([
    "field",
    "bed",
    "row",
    "greenhouse",
    "highTunnel",
    "greenhouseBed",
    "bench",
    "storageArea",
    "washPack",
    "cooler",
    "freezer",
    "barnShed",
    "other",
  ]),
  parentId: z.string().optional(),
  createdAt: isoDateTimeString,
});

const geoJsonPositionSchema = z.union([
  z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]),
  z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90), z.number()]),
]);

const geoJsonRingSchema = z.array(geoJsonPositionSchema).min(4);

const supportedGeoJsonGeometrySchema = z.union([
  z.object({ type: z.literal("Point"), coordinates: geoJsonPositionSchema }),
  z.object({ type: z.literal("LineString"), coordinates: z.array(geoJsonPositionSchema).min(2) }),
  z.object({ type: z.literal("Polygon"), coordinates: z.array(geoJsonRingSchema).min(1) }),
  z.object({ type: z.literal("MultiPolygon"), coordinates: z.array(z.array(geoJsonRingSchema).min(1)).min(1) }),
]);

const farmMapSettingsSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  addressText: z.string().optional(),
  defaultCenterLatitude: z.number().min(-90).max(90).optional(),
  defaultCenterLongitude: z.number().min(-180).max(180).optional(),
  defaultZoom: z.number().min(0).max(22),
  defaultPitch: z.number().min(0).max(85),
  defaultBearing: z.number().min(0).max(360),
  mapProvider: z.enum(["fallback", "mapLibre"]),
  offlineMapStatus: z.enum(["notConfigured", "notDownloaded", "downloadQueued", "downloading", "downloaded", "failed", "unavailable"]),
  offlinePackName: z.string().optional(),
  offlineDownloadedAt: isoDateTimeString.optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const farmPlaceGeometrySchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  placeId: z.string().optional(),
  geometryType: z.enum(["point", "line", "polygon", "multiPolygon"]),
  geometryRole: z.enum([
    "farmCenter",
    "fieldBoundary",
    "bedBoundary",
    "rowLine",
    "greenhouseBoundary",
    "buildingFootprint",
    "storageArea",
    "washPackArea",
    "bufferZone",
    "waterSource",
    "accessRoad",
    "adjacentLandRiskArea",
    "driftIncidentArea",
    "contaminationConcernPoint",
    "other",
  ]),
  geojson: supportedGeoJsonGeometrySchema,
  source: z.enum(["manualMapEdit", "gps", "addressGeocode", "imported", "derived"]),
  name: z.string().optional(),
  notes: z.string().optional(),
  mapViewLatitude: z.number().min(-90).max(90).optional(),
  mapViewLongitude: z.number().min(-180).max(180).optional(),
  mapViewZoom: z.number().min(0).max(22).optional(),
  mapViewPitch: z.number().min(0).max(85).optional(),
  mapViewBearing: z.number().min(0).max(360).optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
  archivedAt: isoDateTimeString.optional(),
});

const trackedItemSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  kind: z.enum(["crop", "material"]),
  name: z.string().min(1),
  createdAt: isoDateTimeString,
  defaultUnit: z.string().optional(),
});

const farmhandSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  name: z.string().min(1),
  phoneNumber: z.string().optional(),
  notes: z.string().optional(),
  status: z.enum(["active", "inactive"]),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const farmhandRecurringScheduleSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  farmhandId: z.string().min(1),
  weekday: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5), z.literal(6)]),
  startTime: z.string().min(1),
  endTime: z.string().min(1),
  effectiveStartDate: z.string().optional(),
  effectiveEndDate: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const farmhandScheduleSettingsSchema = z.object({
  farmId: z.string().min(1),
  weekStartsOn: z.union([z.literal(0), z.literal(1)]),
  updatedAt: isoDateTimeString,
});

const farmhandWeeklyScheduleBlockSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  farmhandId: z.string().min(1),
  date: z.string().min(1),
  startTime: z.string().min(1),
  endTime: z.string().min(1),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const harvestRecordSchema = z.object({
  id: z.string().min(1),
  kind: z.literal("HarvestRecorded"),
  farmId: z.string().min(1),
  cropId: z.string().min(1),
  sourceLocationId: z.string().min(1),
  quantity: z.object({
    amount: z.number().positive(),
    unit: harvestUnitSchema,
  }),
  createdAt: isoDateTimeString,
  effectiveAt: isoDateTimeString,
  privacy: z.literal("privateToFarm"),
  note: z.string().optional(),
});

const materialUseRecordSchema = z.object({
  id: z.string().min(1),
  kind: z.literal("MaterialUseRecorded"),
  farmId: z.string().min(1),
  materialId: z.string().min(1),
  quantity: z.object({
    amount: z.number().positive(),
    unit: harvestUnitSchema,
  }),
  useLocationId: z.string().optional(),
  createdAt: isoDateTimeString,
  effectiveAt: isoDateTimeString,
  privacy: z.literal("privateToFarm"),
  note: z.string().optional(),
});

const inventoryCountRecordSchema = z.object({
  id: z.string().min(1),
  kind: z.literal("InventoryCountRecorded"),
  farmId: z.string().min(1),
  trackedItemId: z.string().min(1),
  observedQuantity: z.object({
    amount: z.number().min(0),
    unit: harvestUnitSchema,
  }),
  locationId: z.string().optional(),
  createdAt: isoDateTimeString,
  effectiveAt: isoDateTimeString,
  privacy: z.literal("privateToFarm"),
  note: z.string().optional(),
});

const organicOperationProfileSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  organicStatus: z.enum(["notOrganic", "transitioning", "exempt", "certified", "splitOperation"]),
  certifierName: z.string().optional(),
  certifierContact: z.string().optional(),
  certificateNumber: z.string().optional(),
  certificateEffectiveDate: z.string().optional(),
  annualUpdateDueDate: z.string().optional(),
  inspectionDueWindow: z.string().optional(),
  recordRetentionYears: z.number().int().positive(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicCertificationScopeSchema = z.object({
  profileId: z.string().min(1),
  farmId: z.string().min(1),
  scopeType: z.enum([
    "crops",
    "livestock",
    "wildCrops",
    "handling",
    "mushrooms",
    "producerGroup",
    "imports",
    "packagedProductLabeling",
  ]),
  enabled: z.boolean(),
  status: z.enum(["active", "planned", "notApplicable"]),
  certifierNotes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicPlaceProfileSchema = z.object({
  farmId: z.string().min(1),
  placeId: z.string().min(1),
  organicStatus: z.enum(["nonOrganic", "transitioning", "eligibleOrganic", "certifiedOrganic", "buffer", "excluded"]),
  transitionStartDate: z.string().optional(),
  lastProhibitedSubstanceDate: z.string().optional(),
  organicEligibilityDate: z.string().optional(),
  certifiedOrganicSinceDate: z.string().optional(),
  boundaryDescription: z.string().optional(),
  bufferDescription: z.string().optional(),
  adjacentLandUse: z.string().optional(),
  contaminationRisks: z.string().optional(),
  certifierApproved: z.boolean(),
  certifierNotes: z.string().optional(),
  evidenceAttachmentIds: z.array(z.string()),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicBoundaryEvidenceSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  placeId: z.string().min(1),
  evidenceType: z.enum(["photo", "map", "note", "document"]),
  description: z.string().min(1),
  attachmentUri: z.string().optional(),
  capturedAt: isoDateTimeString,
  createdAt: isoDateTimeString,
});

const organicInputSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  materialId: z.string().optional(),
  name: z.string().min(1),
  inputCategory: z.enum([
    "fertility",
    "compost",
    "manure",
    "seedTreatment",
    "pestControl",
    "diseaseControl",
    "weedControl",
    "livestockHealth",
    "cleaning",
    "handling",
    "packaging",
    "other",
  ]),
  manufacturer: z.string().optional(),
  supplier: z.string().optional(),
  composition: z.string().optional(),
  source: z.string().optional(),
  approvalStatus: z.enum([
    "unknown",
    "approvedByCertifier",
    "omriListed",
    "wsdaListed",
    "allowedByNationalList",
    "restricted",
    "prohibited",
    "needsReview",
  ]),
  approvalEvidenceAttachmentIds: z.array(z.string()),
  certifierApprovalDate: z.string().optional(),
  approvalExpirationDate: z.string().optional(),
  restrictions: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicInputApplicationSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  inputId: z.string().min(1),
  placeId: z.string().optional(),
  cropId: z.string().optional(),
  date: isoDateTimeString,
  quantity: z.string().optional(),
  unit: z.string().optional(),
  rate: z.string().optional(),
  reason: z.string().optional(),
  targetProblem: z.string().optional(),
  weatherNotes: z.string().optional(),
  appliedBy: z.string().optional(),
  evidenceAttachmentIds: z.array(z.string()),
  linkedFarmNoteId: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const seedLotSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  cropId: z.string().optional(),
  variety: z.string().min(1),
  supplier: z.string().optional(),
  lotNumber: z.string().optional(),
  purchaseDate: z.string().optional(),
  quantity: z.string().optional(),
  organicStatus: z.enum(["organic", "untreatedNonOrganic", "treatedAllowed", "treatedProhibited", "unknown"]),
  seedTreatment: z.string().optional(),
  invoiceAttachmentId: z.string().optional(),
  labelAttachmentId: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const commercialAvailabilitySearchSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  seedLotId: z.string().min(1),
  crop: z.string().optional(),
  variety: z.string().optional(),
  searchedOn: z.string().min(1),
  supplierName: z.string().min(1),
  result: z.enum(["available", "unavailable", "wrongVariety", "wrongQuantity", "wrongQuality", "tooLate", "other"]),
  evidenceAttachmentId: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const organicPlantingEventSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  seedLotId: z.string().min(1),
  cropId: z.string().optional(),
  placeId: z.string().optional(),
  date: isoDateTimeString,
  quantityPlanted: z.string().optional(),
  transplantOrDirectSeed: z.enum(["transplant", "directSeed"]).optional(),
  linkedFarmNoteId: z.string().optional(),
  createdAt: isoDateTimeString,
});

const soilFertilityPracticeSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  placeId: z.string().optional(),
  practiceType: z.enum(["coverCrop", "greenManure", "compost", "manure", "mulch", "tillage", "noTill", "soilTest", "erosionControl", "other"]),
  cropId: z.string().optional(),
  date: isoDateTimeString,
  description: z.string().min(1),
  evidenceAttachmentIds: z.array(z.string()),
  linkedFarmNoteId: z.string().optional(),
  createdAt: isoDateTimeString,
});

const compostBatchSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  name: z.string().min(1),
  ingredients: z.string().optional(),
  startDate: z.string().optional(),
  compostingMethod: z.enum(["windrow", "staticAeratedPile", "inVessel", "other"]).optional(),
  initialCNRatio: z.string().optional(),
  status: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const compostTemperatureLogSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  compostBatchId: z.string().min(1),
  date: isoDateTimeString,
  temperatureF: z.number(),
  turned: z.boolean(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const manureApplicationSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  placeId: z.string().optional(),
  cropId: z.string().optional(),
  applicationDate: isoDateTimeString,
  manureType: z.string().optional(),
  incorporated: z.boolean(),
  ediblePortionContactSoil: z.boolean(),
  requiredDaysBeforeHarvest: z.union([z.literal(90), z.literal(120)]),
  earliestHarvestDate: z.string().min(1),
  quantity: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const cropRotationRecordSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  placeId: z.string().optional(),
  cropId: z.string().optional(),
  season: z.string().optional(),
  year: z.number().int(),
  previousCropId: z.string().optional(),
  rotationPurpose: z.enum(["soilOrganicMatter", "pestManagement", "nutrientManagement", "erosionControl"]).optional(),
  coverCropUsed: z.boolean(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const pestWeedDiseaseObservationSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  type: z.enum(["pest", "weed", "disease"]),
  placeId: z.string().optional(),
  cropId: z.string().optional(),
  observedAt: isoDateTimeString,
  severity: z.string().optional(),
  description: z.string().min(1),
  photoAttachmentIds: z.array(z.string()),
  linkedFarmNoteId: z.string().optional(),
  createdAt: isoDateTimeString,
});

const pestWeedDiseaseActionSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  observationId: z.string().min(1),
  actionType: z.enum(["prevention", "sanitation", "cultural", "mechanical", "physical", "biological", "botanical", "allowedSynthetic", "other"]),
  actionDate: isoDateTimeString,
  description: z.string().min(1),
  inputApplicationId: z.string().optional(),
  whyNeeded: z.string().optional(),
  effectivenessNotes: z.string().optional(),
  evidenceAttachmentIds: z.array(z.string()),
  createdAt: isoDateTimeString,
});

const plasticMulchRecordSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  placeId: z.string().optional(),
  cropId: z.string().optional(),
  installedDate: z.string().optional(),
  removedDate: z.string().optional(),
  material: z.string().optional(),
  notes: z.string().optional(),
  evidenceAttachmentIds: z.array(z.string()),
  createdAt: isoDateTimeString,
});

const organicLotSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  lotCode: z.string().min(1),
  cropId: z.string().min(1),
  placeId: z.string().min(1),
  harvestDate: isoDateTimeString,
  organicStatus: z.enum(["organic", "transitioning", "nonOrganic", "unknown"]),
  quantityHarvested: z.number().positive(),
  unit: z.string().min(1),
  createdFromHarvestRecordId: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicHandlingEventSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  lotId: z.string().min(1),
  eventType: z.enum(["wash", "pack", "cool", "dry", "freeze", "sort", "grade", "combine", "split", "relabel", "transport", "other"]),
  eventDate: isoDateTimeString,
  inputLotIds: z.array(z.string()),
  outputLotIds: z.array(z.string()),
  quantityIn: z.number().optional(),
  quantityOut: z.number().optional(),
  unit: z.string().optional(),
  facilityPlaceId: z.string().optional(),
  equipmentUsed: z.string().optional(),
  cleaningRecordId: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const organicStorageRecordSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  lotId: z.string().min(1),
  storagePlaceId: z.string().min(1),
  dateIn: isoDateTimeString,
  dateOut: isoDateTimeString.optional(),
  quantityIn: z.number().positive(),
  quantityOut: z.number().optional(),
  unit: z.string().min(1),
  containerId: z.string().optional(),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const organicSaleRecordSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  lotId: z.string().min(1),
  buyer: z.string().min(1),
  saleDate: isoDateTimeString,
  quantity: z.number().positive(),
  unit: z.string().min(1),
  invoiceNumber: z.string().optional(),
  organicClaim: z.string().optional(),
  evidenceAttachmentIds: z.array(z.string()),
  createdAt: isoDateTimeString,
});

const organicSystemPlanSectionSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  sectionType: z.enum(["practicesProcedures", "inputsSubstances", "monitoring", "recordkeeping", "comminglingPrevention", "additionalInformation"]),
  title: z.string().min(1),
  narrative: z.string().min(1),
  readinessStatus: z.enum(["notStarted", "needsWork", "readyForReview", "notApplicable"]),
  evidenceAttachmentIds: z.array(z.string()),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicInspectionReadinessItemSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  category: z.enum(["profile", "land", "inputs", "seeds", "soil", "pest", "traceability", "records"]),
  prompt: z.string().min(1),
  readinessStatus: z.enum(["notStarted", "needsWork", "readyForReview", "notApplicable"]),
  notes: z.string().optional(),
  evidenceAttachmentIds: z.array(z.string()),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicReportPackageSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  packageType: z.enum(["inspectionPrep", "annualUpdate", "renewalConversation", "recordsArchive"]),
  title: z.string().min(1),
  generatedAt: isoDateTimeString,
  reportNames: z.array(z.string()),
  manifestJson: z.string().min(1),
  packageText: z.string().min(1),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

const organicAdvancedScopeRecordSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  scopeType: z.enum(["livestock", "wildCrops", "mushrooms", "producerGroup", "imports", "labeling"]),
  topic: z.string().min(1),
  description: z.string().min(1),
  readinessStatus: z.enum(["notStarted", "needsWork", "readyForReview", "notApplicable"]),
  evidenceAttachmentIds: z.array(z.string()),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const organicEvidenceLinkSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  farmEventId: z.string().min(1),
  category: z.enum([
    "profile",
    "land",
    "inputApprovals",
    "inputApplications",
    "seeds",
    "soilFertility",
    "compost",
    "manure",
    "pest",
    "lotTraceability",
    "handlingMassBalance",
    "ospPractices",
    "ospRecordkeeping",
    "reports",
    "advancedScope",
    "general",
  ]),
  linkedRecordType: z.enum([
    "organicPlaceProfile",
    "organicBoundaryEvidence",
    "organicInput",
    "organicInputApplication",
    "seedLot",
    "commercialAvailabilitySearch",
    "organicPlantingEvent",
    "soilFertilityPractice",
    "compostBatch",
    "compostTemperatureLog",
    "manureApplication",
    "cropRotationRecord",
    "pestWeedDiseaseObservation",
    "pestWeedDiseaseAction",
    "plasticMulchRecord",
    "organicLot",
    "organicHandlingEvent",
    "organicStorageRecord",
    "organicSaleRecord",
    "organicSystemPlanSection",
    "organicInspectionReadinessItem",
    "organicAdvancedScopeRecord",
    "organicReportPackage",
  ]).optional(),
  linkedRecordId: z.string().optional(),
  evidenceRole: z.enum(["fieldHistory", "photoEvidence", "voiceNote", "labelOrReceipt", "monitoring", "inspectionQuestion", "supportingNote", "other"]),
  notes: z.string().optional(),
  privacy: z.literal("privateToFarm"),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const planningGoalSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  parentGoalId: z.string().optional(),
  placeId: z.string().optional(),
  title: z.string().min(1),
  description: z.string().optional(),
  category: z.enum(["general", "organicCertification", "cropProduction", "soilHealth", "infrastructure", "equipment", "sales", "team"]),
  status: z.enum(["planned", "active", "paused", "completed", "canceled"]),
  targetDate: z.string().optional(),
  source: z.enum(["farmer", "organicCertificationTemplate", "organicCertification"]),
  templateKey: z.string().optional(),
  sortOrder: z.number().int().min(0),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const planningBoardSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  title: z.string().min(1),
  scopeType: z.enum(["goal", "nonGoalTasks"]),
  goalId: z.string().optional(),
  wipLimit: z.number().int().positive().optional(),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const planningTaskSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  goalId: z.string().optional(),
  placeId: z.string().optional(),
  title: z.string().min(1),
  notes: z.string().optional(),
  status: z.enum(["notStarted", "inProgress", "blocked", "done", "canceled"]),
  priority: z.enum(["low", "normal", "high", "urgent"]),
  plannedStartDate: z.string().optional(),
  dueDate: z.string().optional(),
  estimatedMinutes: z.number().int().positive().optional(),
  assignedFarmhandId: z.string().optional(),
  instructionVoiceMemo: z.object({
    localUri: z.string().min(1),
    durationMs: z.number().int().positive().optional(),
    fileSizeBytes: z.number().int().nonnegative().optional(),
  }).optional(),
  instructionPhotos: z.array(z.object({
    localUri: z.string().min(1),
    width: z.number().int().positive().optional(),
    height: z.number().int().positive().optional(),
    mimeType: z.string().optional(),
    fileSizeBytes: z.number().int().nonnegative().optional(),
  })),
  completionNotes: z.string().optional(),
  completedAt: isoDateTimeString.optional(),
  source: z.enum(["farmer", "organicCertificationTemplate", "organicCertification"]),
  templateKey: z.string().optional(),
  sortOrder: z.number().int().min(0),
  createdAt: isoDateTimeString,
  updatedAt: isoDateTimeString,
});

const planningLinkSchema = z.object({
  id: z.string().min(1),
  farmId: z.string().min(1),
  goalId: z.string().optional(),
  taskId: z.string().optional(),
  linkedRecordType: z.enum([
    "farmNote",
    "farmPlace",
    "trackedItem",
    "organicProfile",
    "organicPlaceProfile",
    "organicInput",
    "organicInputApplication",
    "seedLot",
    "organicPlantingEvent",
    "soilFertilityPractice",
    "compostBatch",
    "manureApplication",
    "cropRotationRecord",
    "pestObservation",
    "pestAction",
    "organicLot",
    "organicSystemPlanSection",
    "organicReportPackage",
    "organicAdvancedScopeRecord",
    "organicEvidenceLink",
    "other",
  ]),
  linkedRecordId: z.string().min(1),
  notes: z.string().optional(),
  createdAt: isoDateTimeString,
});

export const mobilePilotRecoveryCopySchema = z.object({
  exportVersion: z.literal(MOBILE_PILOT_RECOVERY_COPY_EXPORT_VERSION),
  createdAt: isoDateTimeString,
  appDataSchemaVersion: z.literal(MOBILE_PILOT_APP_DATA_SCHEMA_VERSION),
  farm: farmSchema,
  locations: z.array(locationSchema),
  farmMapSettings: farmMapSettingsSchema.optional(),
  farmPlaceGeometries: z.array(farmPlaceGeometrySchema),
  farmhands: z.array(farmhandSchema),
  farmhandScheduleSettings: farmhandScheduleSettingsSchema.optional(),
  farmhandRecurringSchedules: z.array(farmhandRecurringScheduleSchema),
  farmhandWeeklyScheduleBlocks: z.array(farmhandWeeklyScheduleBlockSchema),
  trackedItems: z.array(trackedItemSchema),
  harvestRecords: z.array(harvestRecordSchema),
  materialUseRecords: z.array(materialUseRecordSchema),
  inventoryCountRecords: z.array(inventoryCountRecordSchema),
  organicOperationProfile: organicOperationProfileSchema.optional(),
  organicCertificationScopes: z.array(organicCertificationScopeSchema),
  organicPlaceProfiles: z.array(organicPlaceProfileSchema),
  organicBoundaryEvidence: z.array(organicBoundaryEvidenceSchema),
  organicInputs: z.array(organicInputSchema),
  organicInputApplications: z.array(organicInputApplicationSchema),
  seedLots: z.array(seedLotSchema),
  commercialAvailabilitySearches: z.array(commercialAvailabilitySearchSchema),
  organicPlantingEvents: z.array(organicPlantingEventSchema),
  soilFertilityPractices: z.array(soilFertilityPracticeSchema),
  compostBatches: z.array(compostBatchSchema),
  compostTemperatureLogs: z.array(compostTemperatureLogSchema),
  manureApplications: z.array(manureApplicationSchema),
  cropRotationRecords: z.array(cropRotationRecordSchema),
  pestWeedDiseaseObservations: z.array(pestWeedDiseaseObservationSchema),
  pestWeedDiseaseActions: z.array(pestWeedDiseaseActionSchema),
  plasticMulchRecords: z.array(plasticMulchRecordSchema),
  organicLots: z.array(organicLotSchema),
  organicHandlingEvents: z.array(organicHandlingEventSchema),
  organicStorageRecords: z.array(organicStorageRecordSchema),
  organicSaleRecords: z.array(organicSaleRecordSchema),
  organicSystemPlanSections: z.array(organicSystemPlanSectionSchema),
  organicInspectionReadinessItems: z.array(organicInspectionReadinessItemSchema),
  organicReportPackages: z.array(organicReportPackageSchema),
  organicAdvancedScopeRecords: z.array(organicAdvancedScopeRecordSchema),
  organicEvidenceLinks: z.array(organicEvidenceLinkSchema),
  planningGoals: z.array(planningGoalSchema),
  planningBoards: z.array(planningBoardSchema),
  planningTasks: z.array(planningTaskSchema),
  planningLinks: z.array(planningLinkSchema),
});
