import type { Migration } from "./migrationRunner";

export const createOrganicInputs: Migration = {
  version: 11,
  name: "create_organic_inputs",
  statements: [
    `CREATE TABLE IF NOT EXISTS organic_inputs (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      material_id TEXT,
      name TEXT NOT NULL,
      input_category TEXT NOT NULL CHECK (input_category IN ('fertility', 'compost', 'manure', 'seedTreatment', 'pestControl', 'diseaseControl', 'weedControl', 'livestockHealth', 'cleaning', 'handling', 'packaging', 'other')),
      manufacturer TEXT,
      supplier TEXT,
      composition TEXT,
      source TEXT,
      approval_status TEXT NOT NULL CHECK (approval_status IN ('unknown', 'approvedByCertifier', 'omriListed', 'wsdaListed', 'allowedByNationalList', 'restricted', 'prohibited', 'needsReview')),
      approval_evidence_attachment_ids_json TEXT NOT NULL DEFAULT '[]',
      certifier_approval_date TEXT,
      approval_expiration_date TEXT,
      restrictions TEXT,
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (material_id) REFERENCES tracked_items(id)
    );`,
    `CREATE TABLE IF NOT EXISTS organic_input_applications (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      input_id TEXT NOT NULL,
      place_id TEXT,
      crop_id TEXT,
      date TEXT NOT NULL,
      quantity TEXT,
      unit TEXT,
      rate TEXT,
      reason TEXT,
      target_problem TEXT,
      weather_notes TEXT,
      applied_by TEXT,
      evidence_attachment_ids_json TEXT NOT NULL DEFAULT '[]',
      linked_farm_note_id TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (input_id) REFERENCES organic_inputs(id),
      FOREIGN KEY (place_id) REFERENCES farm_locations(id),
      FOREIGN KEY (crop_id) REFERENCES tracked_items(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_organic_inputs_farm ON organic_inputs(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_organic_input_applications_farm ON organic_input_applications(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_organic_input_applications_input ON organic_input_applications(input_id);",
  ],
};
