import type { Migration } from "./migrationRunner";

export const createOrganicSoil: Migration = {
  version: 13,
  name: "create_organic_soil",
  statements: [
    `CREATE TABLE IF NOT EXISTS soil_fertility_practices (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      place_id TEXT,
      practice_type TEXT NOT NULL,
      crop_id TEXT,
      date TEXT NOT NULL,
      description TEXT NOT NULL,
      evidence_attachment_ids_json TEXT NOT NULL DEFAULT '[]',
      linked_farm_note_id TEXT,
      created_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (place_id) REFERENCES farm_locations(id),
      FOREIGN KEY (crop_id) REFERENCES tracked_items(id)
    );`,
    `CREATE TABLE IF NOT EXISTS compost_batches (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      name TEXT NOT NULL,
      ingredients TEXT,
      start_date TEXT,
      composting_method TEXT CHECK (composting_method IN ('windrow', 'staticAeratedPile', 'inVessel', 'other')),
      initial_cn_ratio TEXT,
      status TEXT,
      notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id)
    );`,
    `CREATE TABLE IF NOT EXISTS compost_temperature_logs (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      compost_batch_id TEXT NOT NULL,
      date TEXT NOT NULL,
      temperature_f REAL NOT NULL,
      turned INTEGER NOT NULL CHECK (turned IN (0, 1)),
      notes TEXT,
      created_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (compost_batch_id) REFERENCES compost_batches(id)
    );`,
    `CREATE TABLE IF NOT EXISTS manure_applications (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      place_id TEXT,
      crop_id TEXT,
      application_date TEXT NOT NULL,
      manure_type TEXT,
      incorporated INTEGER NOT NULL CHECK (incorporated IN (0, 1)),
      edible_portion_contact_soil INTEGER NOT NULL CHECK (edible_portion_contact_soil IN (0, 1)),
      required_days_before_harvest INTEGER NOT NULL CHECK (required_days_before_harvest IN (90, 120)),
      earliest_harvest_date TEXT NOT NULL,
      quantity TEXT,
      notes TEXT,
      created_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (place_id) REFERENCES farm_locations(id),
      FOREIGN KEY (crop_id) REFERENCES tracked_items(id)
    );`,
    `CREATE TABLE IF NOT EXISTS crop_rotation_records (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      place_id TEXT,
      crop_id TEXT,
      season TEXT,
      year INTEGER NOT NULL,
      previous_crop_id TEXT,
      rotation_purpose TEXT CHECK (rotation_purpose IN ('soilOrganicMatter', 'pestManagement', 'nutrientManagement', 'erosionControl')),
      cover_crop_used INTEGER NOT NULL CHECK (cover_crop_used IN (0, 1)),
      notes TEXT,
      created_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (place_id) REFERENCES farm_locations(id),
      FOREIGN KEY (crop_id) REFERENCES tracked_items(id),
      FOREIGN KEY (previous_crop_id) REFERENCES tracked_items(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_soil_fertility_practices_farm ON soil_fertility_practices(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_compost_batches_farm ON compost_batches(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_manure_applications_farm ON manure_applications(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_crop_rotation_records_farm ON crop_rotation_records(farm_id);",
  ],
};
