import type { Migration } from "./migrationRunner";

export const createPlanning: Migration = {
  version: 20,
  name: "create_planning",
  statements: [
    `CREATE TABLE IF NOT EXISTS planning_goals (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      parent_goal_id TEXT,
      title TEXT NOT NULL,
      description TEXT,
      category TEXT NOT NULL CHECK (category IN ('general', 'organicCertification', 'cropProduction', 'soilHealth', 'infrastructure', 'equipment', 'sales', 'team')),
      status TEXT NOT NULL CHECK (status IN ('planned', 'active', 'paused', 'completed', 'canceled')),
      target_date TEXT,
      source TEXT NOT NULL CHECK (source IN ('farmer', 'organicCertificationTemplate', 'organicCertification')),
      template_key TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (parent_goal_id) REFERENCES planning_goals(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_goals_farm ON planning_goals(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_goals_parent ON planning_goals(farm_id, parent_goal_id);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_planning_goals_template ON planning_goals(farm_id, template_key) WHERE template_key IS NOT NULL;",
    `CREATE TABLE IF NOT EXISTS planning_tasks (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      goal_id TEXT,
      title TEXT NOT NULL,
      notes TEXT,
      status TEXT NOT NULL CHECK (status IN ('notStarted', 'inProgress', 'blocked', 'done', 'canceled')),
      priority TEXT NOT NULL CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
      planned_start_date TEXT,
      due_date TEXT,
      estimated_minutes INTEGER,
      assigned_farmhand_id TEXT,
      instruction_voice_memo_local_uri TEXT,
      instruction_voice_memo_duration_ms INTEGER,
      instruction_voice_memo_file_size_bytes INTEGER,
      instruction_photo_json TEXT NOT NULL DEFAULT '[]',
      completion_notes TEXT,
      completed_at TEXT,
      source TEXT NOT NULL CHECK (source IN ('farmer', 'organicCertificationTemplate', 'organicCertification')),
      template_key TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (goal_id) REFERENCES planning_goals(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_tasks_farm ON planning_tasks(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_tasks_goal ON planning_tasks(farm_id, goal_id);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_planning_tasks_template ON planning_tasks(farm_id, template_key) WHERE template_key IS NOT NULL;",
    `CREATE TABLE IF NOT EXISTS planning_links (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      goal_id TEXT,
      task_id TEXT,
      linked_record_type TEXT NOT NULL CHECK (linked_record_type IN ('farmNote', 'farmPlace', 'trackedItem', 'organicProfile', 'organicPlaceProfile', 'organicInput', 'organicInputApplication', 'seedLot', 'organicPlantingEvent', 'soilFertilityPractice', 'compostBatch', 'manureApplication', 'cropRotationRecord', 'pestObservation', 'pestAction', 'organicLot', 'organicSystemPlanSection', 'organicReportPackage', 'organicAdvancedScopeRecord', 'organicEvidenceLink', 'other')),
      linked_record_id TEXT NOT NULL,
      notes TEXT,
      created_at TEXT NOT NULL,
      CHECK (goal_id IS NOT NULL OR task_id IS NOT NULL),
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (goal_id) REFERENCES planning_goals(id),
      FOREIGN KEY (task_id) REFERENCES planning_tasks(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_links_goal ON planning_links(farm_id, goal_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_links_task ON planning_links(farm_id, task_id);",
  ],
};
