import type { Migration } from "./migrationRunner";

export const createPlanning: Migration = {
  version: 20,
  name: "create_planning",
  statements: [
    `CREATE TABLE IF NOT EXISTS planning_goals (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      parent_goal_id TEXT,
      place_id TEXT,
      title TEXT NOT NULL,
      description TEXT,
      category TEXT NOT NULL CHECK (category IN ('general', 'organicCertification', 'cropProduction', 'soilHealth', 'infrastructure', 'equipment', 'sales', 'team')),
      status TEXT NOT NULL CHECK (status IN ('planned', 'active', 'paused', 'completed', 'canceled')),
      target_date TEXT,
      source TEXT NOT NULL CHECK (source IN ('farmer', 'organicCertificationTemplate', 'organicCertification')),
      template_key TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (parent_goal_id) REFERENCES planning_goals(id),
      FOREIGN KEY (place_id) REFERENCES farm_locations(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_goals_farm ON planning_goals(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_goals_parent ON planning_goals(farm_id, parent_goal_id);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_planning_goals_template ON planning_goals(farm_id, template_key) WHERE template_key IS NOT NULL;",
    `CREATE TABLE IF NOT EXISTS planning_periods (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      label TEXT NOT NULL,
      period_type TEXT NOT NULL CHECK (period_type IN ('day', 'week', 'twoWeeks', 'month', 'season', 'year', 'custom')),
      start_date TEXT,
      end_date TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_periods_farm ON planning_periods(farm_id);",
    `CREATE TABLE IF NOT EXISTS planning_tasks (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      goal_id TEXT,
      period_id TEXT,
      place_id TEXT,
      title TEXT NOT NULL,
      notes TEXT,
      status TEXT NOT NULL CHECK (status IN ('notStarted', 'ready', 'inProgress', 'blocked', 'done', 'canceled')),
      priority TEXT NOT NULL CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
      planned_start_date TEXT,
      due_date TEXT,
      estimated_minutes INTEGER,
      responsible_person TEXT,
      completion_notes TEXT,
      completed_at TEXT,
      source TEXT NOT NULL CHECK (source IN ('farmer', 'organicCertificationTemplate', 'organicCertification')),
      template_key TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (goal_id) REFERENCES planning_goals(id),
      FOREIGN KEY (period_id) REFERENCES planning_periods(id),
      FOREIGN KEY (place_id) REFERENCES farm_locations(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_tasks_farm ON planning_tasks(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_tasks_goal ON planning_tasks(farm_id, goal_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_tasks_period ON planning_tasks(farm_id, period_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_goals_place ON planning_goals(farm_id, place_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_tasks_place ON planning_tasks(farm_id, place_id);",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_planning_tasks_template ON planning_tasks(farm_id, template_key) WHERE template_key IS NOT NULL;",
    `CREATE TABLE IF NOT EXISTS planning_links (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      goal_id TEXT,
      task_id TEXT,
      linked_record_type TEXT NOT NULL CHECK (linked_record_type IN ('farmNote', 'farmPlace', 'trackedItem', 'organicProfile', 'organicPlaceProfile', 'organicInput', 'organicInputApplication', 'seedLot', 'organicPlantingEvent', 'soilFertilityPractice', 'compostBatch', 'manureApplication', 'cropRotationRecord', 'pestObservation', 'pestAction', 'organicLot', 'organicSystemPlanSection', 'organicReportPackage', 'organicAdvancedScopeRecord', 'organicEvidenceLink', 'other')),
      linked_record_id TEXT NOT NULL,
      notes TEXT,
      created_at TEXT NOT NULL,
      CHECK (goal_id IS NOT NULL OR task_id IS NOT NULL),
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (goal_id) REFERENCES planning_goals(id),
      FOREIGN KEY (task_id) REFERENCES planning_tasks(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_links_goal ON planning_links(farm_id, goal_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_links_task ON planning_links(farm_id, task_id);",
    `CREATE TABLE IF NOT EXISTS planning_boards (
      id TEXT PRIMARY KEY NOT NULL,
      farm_id TEXT NOT NULL,
      title TEXT NOT NULL,
      scope_type TEXT NOT NULL CHECK (scope_type IN ('goal', 'nonGoalTasks')),
      goal_id TEXT,
      wip_limit INTEGER,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      CHECK ((scope_type = 'goal' AND goal_id IS NOT NULL) OR (scope_type = 'nonGoalTasks' AND goal_id IS NULL)),
      FOREIGN KEY (farm_id) REFERENCES farms(id),
      FOREIGN KEY (goal_id) REFERENCES planning_goals(id)
    );`,
    "CREATE INDEX IF NOT EXISTS idx_planning_boards_farm ON planning_boards(farm_id);",
    "CREATE INDEX IF NOT EXISTS idx_planning_boards_goal ON planning_boards(farm_id, goal_id);",
  ],
};
